timezone: Asia/Taipei
locale:
  main: en_US.UTF-8
  install:
    - en_US.UTF-8 UTF-8
    - zh_TW.UTF-8 UTF-8
    - ja_JP.UTF-8 UTF-8
services:
  - name: dockerd
    options: {}
  - name: mcp-terminal
    options:
      host_path: ./mcp
      container_path: /mcp
      skill_path: ./skills/mcp-terminal-operator
ai-cli-tools:
  - codex
  - gemini
  - opencode
packages:
  - name: System Packages
    pacman:
      - openssh
      - python-pwntools
      - checksec
    yay:
      - python-mcp
    gem:
      - seccomp-tools
    npm: []
    pip: []
custom_install_commands:
  - command: npm install -g pnpm
    run_as: root
  - command: go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
    run_as: agent
prompt_file: ./prompt/sandbox.md
skills: []
sandbox_env_skill_path: ./.sandbox_generated/skills/sandbox-environment-hint
image_name: agent-sandbox
container_name_prefix: agent-sandbox
workspace_host_path: /home/p23/ctf/midnightflag2026/heap
workspace_container_path: /home/agent/challenge
startup_script_host_path: ./script/startup.sh
codex_auth_host_path: ~/.codex/auth.json
codex_config_host_path: ~/.codex/config.toml
gemini_auth_host_path: ~/.gemini/oauth_creds.json
gemini_config_host_path: ~/.gemini/settings.json
opencode_auth_host_path: ~/.local/share/opencode/auth.json
opencode_config_host_path: ~/.config/opencode/opencode.json
